name: CapitalConceptual
favicon: null
layout_spectrum: 0.6364982242230326
typography_spectrum: 0.1850661071948707
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.781568695558235
  lightness: 0.49073789408430457
  saturation: 0.9445149323437363
  rhythmicContrast: 0.5382284463848919
purpose: []
